fix(Prover CLI): `status batch` bugs (#1865)
## What ❔

<!-- What are the changes this PR brings about? -->
<!-- Example: This PR adds a PR template to the repo. -->
<!-- (For bigger PRs adding more context is appreciated) -->

1. Fix the case where the prover job is in `in_gpu_proof` status.
2. Fix `BatchData` default implementation.
3. Fix `From<Vec<WitnessJobStatus>>` and `From<Vec<ProverJobFriInfo>>`

## Why ❔

<!-- Why are these changes done? What goal do they contribute to? What
are the principles behind them? -->
<!-- Example: PR templates ensure PR reviewers, observers, and future
iterators are in context about the evolution of repos. -->

1. It panics when you run the `status batch` command in a GPU prover:

```
in_gpu_proof
thread 'main' panicked at /home/admin/zksync-era-2/prover/prover_dal/src/fri_prover_dal.rs:679:64:
called `Result::unwrap()` on an `Err` value: VariantNotFound
```
2. Recursion tip `AggregationRoundInfo` in `BatchData` default
implementation was wrong.
3. `InProgress` and `Successful` status were mixed up in
`From<Vec<WitnessJobStatus>>` and `From<Vec<ProverJobFriInfo>>`

## Checklist

<!-- Check your PR fulfills the following items. -->
<!-- For draft PRs check the boxes as you complete them. -->

- [x] PR title corresponds to the body of PR (we generate changelog
entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `zk fmt` and `zk lint`.
- [x] Spellcheck has been run via `zk spellcheck`.
- [x] Linkcheck has been run via `zk linkcheck`.

---------

Co-authored-by: Joaquin Carletti <56092489+ColoCarletti@users.noreply.github.com>
Co-authored-by: Joaquin Carletti <joaquin.carletti@lambdaclass.com>
Co-authored-by: AnastasiiaVashchuk <72273339+AnastasiiaVashchuk@users.noreply.github.com>
Co-authored-by: Artem Fomiuk <88630083+Artemka374@users.noreply.github.com>