chore(docs): adds instructions for `Cannot read properties of undefined (reading 'compilerPath')` error resolution (#2642)
Encountered an issue when setting up new development environment: when
running `zk init`, it would fail with the following error:

```text
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
$ ts-node scripts/compile-yul.ts compile-precompiles
Using zksolc from https://github.com/matter-labs/era-compiler-solidity/releases/download/prerelease-a167aa3-code4rena/zksolc-macosx-arm64-v1.5.0
Yarn project directory: /Users/jacob/Projects/zksync-era/contracts/system-contracts
Error: Cannot read properties of undefined (reading 'compilerPath')
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
```

Thus, this PR updates the "Troubleshooting" section of
`docs/guides/launch.md` with the resolution instructions.