fix(EN): properly set chain_id for old batch transactions (#4488)
## What ❔

If received batch details contain None/Null chain_id (commit_chain_id,
prove_chain_id, execute_chain_id) set it to config provided chain id for
L1. This happens for old batches.

## Why ❔

If you try syning EN from scratch with a "old" chain you will encounter
following error:
```
Error: One or more tasks failed: ["Task transaction_finality_updater failed: No batch transactions to process for chain id 1 while there are some for None chain_id.Error is thrown so node can restart and reload SL data. If node doesn't make any progress after restart, then it's bug, please contact developers."]
```

Logic for fetching batch transactions to process their finality status
assumes chain_ids are set properly and no transaction should have
chain_id = None. However this is the case for old chains. When fetching
they return *_chain_id: null in zks_getL1BatchDetails for some old
batches.

## Is this a breaking change?
- [ ] Yes
- [ ] No

## Operational changes
<!-- Any config changes? Any new flags? Any changes to any scripts? -->
<!-- Please add anything that non-Matter Labs entities running their own
ZK Chain may need to know -->

## Checklist

<!-- Check your PR fulfills the following items. -->
<!-- For draft PRs check the boxes as you complete them. -->

- [ ] PR title corresponds to the body of PR (we generate changelog
entries from PRs).
- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] Code has been formatted via `zkstack dev fmt` and `zkstack dev
lint`.