fix(tee-prover): fix deserialization of duration in envy config
Relevant logs from the `stage` environment showcasing the issue:
https://grafana.matterlabs.dev/goto/IC-9k4eIR?orgId=1

Error message from the above logs:
```
Error: missing value for field initial_retry_backoff
```

The root cause of the problem supposedly boils down to the mismatch
between the expected format of `TEE_PROVER_INITIAL_RETRY_BACKOFF` and
the actual format. We export it as follows:
```
export TEE_PROVER_INITIAL_RETRY_BACKOFF=1
```
which is not supported as explained here:
https://github.com/serde-rs/serde/issues/339#issuecomment-539453327